version: '3.7'
services:
  app:
    build:
      context: .
      target: test
      dockerfile: ./Dockerfile
    networks:
      - testing
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/2
  redis:
    image: redis:7.0.0-alpine
    ports:
      - 6379:6379
    networks:
      - testing

networks:
  testing: {}
