version: '3.7'
services:
  app:
    build:
      context: .
      target: bin
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - redis
    networks:
      - internal
    environment:
      - REDIS_URL=redis://redis:6379/1
  redis:
    image: redis:7.0.0-alpine
    networks:
      - internal

networks:
  internal: {}
